// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raphael-foliveira/tca/pkg/models"
	"github.com/raphael-foliveira/tca/pkg/tools"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgent creates a new instance of MockAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgent {
	mock := &MockAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgent is an autogenerated mock type for the Agent type
type MockAgent struct {
	mock.Mock
}

type MockAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgent) EXPECT() *MockAgent_Expecter {
	return &MockAgent_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function for the type MockAgent
func (_mock *MockAgent) Invoke(ctx context.Context, checkpoint models.Checkpoint, userMessage string, tools1 ...*tools.Tool) (models.Checkpoint, error) {
	var tmpRet mock.Arguments
	if len(tools1) > 0 {
		tmpRet = _mock.Called(ctx, checkpoint, userMessage, tools1)
	} else {
		tmpRet = _mock.Called(ctx, checkpoint, userMessage)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 models.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint, string, ...*tools.Tool) (models.Checkpoint, error)); ok {
		return returnFunc(ctx, checkpoint, userMessage, tools1...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint, string, ...*tools.Tool) models.Checkpoint); ok {
		r0 = returnFunc(ctx, checkpoint, userMessage, tools1...)
	} else {
		r0 = ret.Get(0).(models.Checkpoint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Checkpoint, string, ...*tools.Tool) error); ok {
		r1 = returnFunc(ctx, checkpoint, userMessage, tools1...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgent_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type MockAgent_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpoint models.Checkpoint
//   - userMessage string
//   - tools1 ...*tools.Tool
func (_e *MockAgent_Expecter) Invoke(ctx interface{}, checkpoint interface{}, userMessage interface{}, tools1 ...interface{}) *MockAgent_Invoke_Call {
	return &MockAgent_Invoke_Call{Call: _e.mock.On("Invoke",
		append([]interface{}{ctx, checkpoint, userMessage}, tools1...)...)}
}

func (_c *MockAgent_Invoke_Call) Run(run func(ctx context.Context, checkpoint models.Checkpoint, userMessage string, tools1 ...*tools.Tool)) *MockAgent_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Checkpoint
		if args[1] != nil {
			arg1 = args[1].(models.Checkpoint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*tools.Tool
		var variadicArgs []*tools.Tool
		if len(args) > 3 {
			variadicArgs = args[3].([]*tools.Tool)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockAgent_Invoke_Call) Return(checkpoint1 models.Checkpoint, err error) *MockAgent_Invoke_Call {
	_c.Call.Return(checkpoint1, err)
	return _c
}

func (_c *MockAgent_Invoke_Call) RunAndReturn(run func(ctx context.Context, checkpoint models.Checkpoint, userMessage string, tools1 ...*tools.Tool) (models.Checkpoint, error)) *MockAgent_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// InvokeStream provides a mock function for the type MockAgent
func (_mock *MockAgent) InvokeStream(ctx context.Context, checkpoint models.Checkpoint, userMessage string, onContent func(string) error, tools1 ...*tools.Tool) (models.Checkpoint, error) {
	var tmpRet mock.Arguments
	if len(tools1) > 0 {
		tmpRet = _mock.Called(ctx, checkpoint, userMessage, onContent, tools1)
	} else {
		tmpRet = _mock.Called(ctx, checkpoint, userMessage, onContent)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InvokeStream")
	}

	var r0 models.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint, string, func(string) error, ...*tools.Tool) (models.Checkpoint, error)); ok {
		return returnFunc(ctx, checkpoint, userMessage, onContent, tools1...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint, string, func(string) error, ...*tools.Tool) models.Checkpoint); ok {
		r0 = returnFunc(ctx, checkpoint, userMessage, onContent, tools1...)
	} else {
		r0 = ret.Get(0).(models.Checkpoint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Checkpoint, string, func(string) error, ...*tools.Tool) error); ok {
		r1 = returnFunc(ctx, checkpoint, userMessage, onContent, tools1...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgent_InvokeStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeStream'
type MockAgent_InvokeStream_Call struct {
	*mock.Call
}

// InvokeStream is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpoint models.Checkpoint
//   - userMessage string
//   - onContent func(string) error
//   - tools1 ...*tools.Tool
func (_e *MockAgent_Expecter) InvokeStream(ctx interface{}, checkpoint interface{}, userMessage interface{}, onContent interface{}, tools1 ...interface{}) *MockAgent_InvokeStream_Call {
	return &MockAgent_InvokeStream_Call{Call: _e.mock.On("InvokeStream",
		append([]interface{}{ctx, checkpoint, userMessage, onContent}, tools1...)...)}
}

func (_c *MockAgent_InvokeStream_Call) Run(run func(ctx context.Context, checkpoint models.Checkpoint, userMessage string, onContent func(string) error, tools1 ...*tools.Tool)) *MockAgent_InvokeStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Checkpoint
		if args[1] != nil {
			arg1 = args[1].(models.Checkpoint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 func(string) error
		if args[3] != nil {
			arg3 = args[3].(func(string) error)
		}
		var arg4 []*tools.Tool
		var variadicArgs []*tools.Tool
		if len(args) > 4 {
			variadicArgs = args[4].([]*tools.Tool)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockAgent_InvokeStream_Call) Return(checkpoint1 models.Checkpoint, err error) *MockAgent_InvokeStream_Call {
	_c.Call.Return(checkpoint1, err)
	return _c
}

func (_c *MockAgent_InvokeStream_Call) RunAndReturn(run func(ctx context.Context, checkpoint models.Checkpoint, userMessage string, onContent func(string) error, tools1 ...*tools.Tool) (models.Checkpoint, error)) *MockAgent_InvokeStream_Call {
	_c.Call.Return(run)
	return _c
}
