// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raphael-foliveira/tca/pkg/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatCompletionClient creates a new instance of MockChatCompletionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatCompletionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatCompletionClient {
	mock := &MockChatCompletionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatCompletionClient is an autogenerated mock type for the ChatCompletionClient type
type MockChatCompletionClient struct {
	mock.Mock
}

type MockChatCompletionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatCompletionClient) EXPECT() *MockChatCompletionClient_Expecter {
	return &MockChatCompletionClient_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type MockChatCompletionClient
func (_mock *MockChatCompletionClient) Complete(ctx context.Context, req agent.ChatCompletionRequest) (agent.ChatCompletionResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 agent.ChatCompletionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.ChatCompletionRequest) (agent.ChatCompletionResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.ChatCompletionRequest) agent.ChatCompletionResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(agent.ChatCompletionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, agent.ChatCompletionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatCompletionClient_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockChatCompletionClient_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - req agent.ChatCompletionRequest
func (_e *MockChatCompletionClient_Expecter) Complete(ctx interface{}, req interface{}) *MockChatCompletionClient_Complete_Call {
	return &MockChatCompletionClient_Complete_Call{Call: _e.mock.On("Complete", ctx, req)}
}

func (_c *MockChatCompletionClient_Complete_Call) Run(run func(ctx context.Context, req agent.ChatCompletionRequest)) *MockChatCompletionClient_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 agent.ChatCompletionRequest
		if args[1] != nil {
			arg1 = args[1].(agent.ChatCompletionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCompletionClient_Complete_Call) Return(chatCompletionResponse agent.ChatCompletionResponse, err error) *MockChatCompletionClient_Complete_Call {
	_c.Call.Return(chatCompletionResponse, err)
	return _c
}

func (_c *MockChatCompletionClient_Complete_Call) RunAndReturn(run func(ctx context.Context, req agent.ChatCompletionRequest) (agent.ChatCompletionResponse, error)) *MockChatCompletionClient_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteStreaming provides a mock function for the type MockChatCompletionClient
func (_mock *MockChatCompletionClient) CompleteStreaming(ctx context.Context, req agent.ChatCompletionRequest, onDelta func(content string) error) (agent.ChatCompletionResponse, error) {
	ret := _mock.Called(ctx, req, onDelta)

	if len(ret) == 0 {
		panic("no return value specified for CompleteStreaming")
	}

	var r0 agent.ChatCompletionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.ChatCompletionRequest, func(content string) error) (agent.ChatCompletionResponse, error)); ok {
		return returnFunc(ctx, req, onDelta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, agent.ChatCompletionRequest, func(content string) error) agent.ChatCompletionResponse); ok {
		r0 = returnFunc(ctx, req, onDelta)
	} else {
		r0 = ret.Get(0).(agent.ChatCompletionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, agent.ChatCompletionRequest, func(content string) error) error); ok {
		r1 = returnFunc(ctx, req, onDelta)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatCompletionClient_CompleteStreaming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteStreaming'
type MockChatCompletionClient_CompleteStreaming_Call struct {
	*mock.Call
}

// CompleteStreaming is a helper method to define mock.On call
//   - ctx context.Context
//   - req agent.ChatCompletionRequest
//   - onDelta func(content string) error
func (_e *MockChatCompletionClient_Expecter) CompleteStreaming(ctx interface{}, req interface{}, onDelta interface{}) *MockChatCompletionClient_CompleteStreaming_Call {
	return &MockChatCompletionClient_CompleteStreaming_Call{Call: _e.mock.On("CompleteStreaming", ctx, req, onDelta)}
}

func (_c *MockChatCompletionClient_CompleteStreaming_Call) Run(run func(ctx context.Context, req agent.ChatCompletionRequest, onDelta func(content string) error)) *MockChatCompletionClient_CompleteStreaming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 agent.ChatCompletionRequest
		if args[1] != nil {
			arg1 = args[1].(agent.ChatCompletionRequest)
		}
		var arg2 func(content string) error
		if args[2] != nil {
			arg2 = args[2].(func(content string) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatCompletionClient_CompleteStreaming_Call) Return(chatCompletionResponse agent.ChatCompletionResponse, err error) *MockChatCompletionClient_CompleteStreaming_Call {
	_c.Call.Return(chatCompletionResponse, err)
	return _c
}

func (_c *MockChatCompletionClient_CompleteStreaming_Call) RunAndReturn(run func(ctx context.Context, req agent.ChatCompletionRequest, onDelta func(content string) error) (agent.ChatCompletionResponse, error)) *MockChatCompletionClient_CompleteStreaming_Call {
	_c.Call.Return(run)
	return _c
}
