// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raphael-foliveira/tca/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatCompletionClient creates a new instance of MockChatCompletionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatCompletionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatCompletionClient {
	mock := &MockChatCompletionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatCompletionClient is an autogenerated mock type for the ChatCompletionClient type
type MockChatCompletionClient struct {
	mock.Mock
}

type MockChatCompletionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatCompletionClient) EXPECT() *MockChatCompletionClient_Expecter {
	return &MockChatCompletionClient_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockChatCompletionClient
func (_mock *MockChatCompletionClient) New(ctx context.Context, params client.ChatCompletionParams) (*client.ChatCompletion, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 *client.ChatCompletion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ChatCompletionParams) (*client.ChatCompletion, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ChatCompletionParams) *client.ChatCompletion); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ChatCompletion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ChatCompletionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatCompletionClient_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockChatCompletionClient_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
//   - params client.ChatCompletionParams
func (_e *MockChatCompletionClient_Expecter) New(ctx interface{}, params interface{}) *MockChatCompletionClient_New_Call {
	return &MockChatCompletionClient_New_Call{Call: _e.mock.On("New", ctx, params)}
}

func (_c *MockChatCompletionClient_New_Call) Run(run func(ctx context.Context, params client.ChatCompletionParams)) *MockChatCompletionClient_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ChatCompletionParams
		if args[1] != nil {
			arg1 = args[1].(client.ChatCompletionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCompletionClient_New_Call) Return(chatCompletion *client.ChatCompletion, err error) *MockChatCompletionClient_New_Call {
	_c.Call.Return(chatCompletion, err)
	return _c
}

func (_c *MockChatCompletionClient_New_Call) RunAndReturn(run func(ctx context.Context, params client.ChatCompletionParams) (*client.ChatCompletion, error)) *MockChatCompletionClient_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewStreaming provides a mock function for the type MockChatCompletionClient
func (_mock *MockChatCompletionClient) NewStreaming(ctx context.Context, params client.ChatCompletionParams) client.ChatCompletionStream {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for NewStreaming")
	}

	var r0 client.ChatCompletionStream
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ChatCompletionParams) client.ChatCompletionStream); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ChatCompletionStream)
		}
	}
	return r0
}

// MockChatCompletionClient_NewStreaming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStreaming'
type MockChatCompletionClient_NewStreaming_Call struct {
	*mock.Call
}

// NewStreaming is a helper method to define mock.On call
//   - ctx context.Context
//   - params client.ChatCompletionParams
func (_e *MockChatCompletionClient_Expecter) NewStreaming(ctx interface{}, params interface{}) *MockChatCompletionClient_NewStreaming_Call {
	return &MockChatCompletionClient_NewStreaming_Call{Call: _e.mock.On("NewStreaming", ctx, params)}
}

func (_c *MockChatCompletionClient_NewStreaming_Call) Run(run func(ctx context.Context, params client.ChatCompletionParams)) *MockChatCompletionClient_NewStreaming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ChatCompletionParams
		if args[1] != nil {
			arg1 = args[1].(client.ChatCompletionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCompletionClient_NewStreaming_Call) Return(chatCompletionStream client.ChatCompletionStream) *MockChatCompletionClient_NewStreaming_Call {
	_c.Call.Return(chatCompletionStream)
	return _c
}

func (_c *MockChatCompletionClient_NewStreaming_Call) RunAndReturn(run func(ctx context.Context, params client.ChatCompletionParams) client.ChatCompletionStream) *MockChatCompletionClient_NewStreaming_Call {
	_c.Call.Return(run)
	return _c
}
