// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/raphael-foliveira/tca/pkg/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatCompletionStream creates a new instance of MockChatCompletionStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatCompletionStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatCompletionStream {
	mock := &MockChatCompletionStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatCompletionStream is an autogenerated mock type for the ChatCompletionStream type
type MockChatCompletionStream struct {
	mock.Mock
}

type MockChatCompletionStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatCompletionStream) EXPECT() *MockChatCompletionStream_Expecter {
	return &MockChatCompletionStream_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockChatCompletionStream
func (_mock *MockChatCompletionStream) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatCompletionStream_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockChatCompletionStream_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockChatCompletionStream_Expecter) Close() *MockChatCompletionStream_Close_Call {
	return &MockChatCompletionStream_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockChatCompletionStream_Close_Call) Run(run func()) *MockChatCompletionStream_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatCompletionStream_Close_Call) Return(err error) *MockChatCompletionStream_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatCompletionStream_Close_Call) RunAndReturn(run func() error) *MockChatCompletionStream_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function for the type MockChatCompletionStream
func (_mock *MockChatCompletionStream) Current() client.ChatCompletionChunk {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 client.ChatCompletionChunk
	if returnFunc, ok := ret.Get(0).(func() client.ChatCompletionChunk); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(client.ChatCompletionChunk)
	}
	return r0
}

// MockChatCompletionStream_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockChatCompletionStream_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
func (_e *MockChatCompletionStream_Expecter) Current() *MockChatCompletionStream_Current_Call {
	return &MockChatCompletionStream_Current_Call{Call: _e.mock.On("Current")}
}

func (_c *MockChatCompletionStream_Current_Call) Run(run func()) *MockChatCompletionStream_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatCompletionStream_Current_Call) Return(chatCompletionChunk client.ChatCompletionChunk) *MockChatCompletionStream_Current_Call {
	_c.Call.Return(chatCompletionChunk)
	return _c
}

func (_c *MockChatCompletionStream_Current_Call) RunAndReturn(run func() client.ChatCompletionChunk) *MockChatCompletionStream_Current_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockChatCompletionStream
func (_mock *MockChatCompletionStream) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatCompletionStream_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockChatCompletionStream_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockChatCompletionStream_Expecter) Err() *MockChatCompletionStream_Err_Call {
	return &MockChatCompletionStream_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockChatCompletionStream_Err_Call) Run(run func()) *MockChatCompletionStream_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatCompletionStream_Err_Call) Return(err error) *MockChatCompletionStream_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatCompletionStream_Err_Call) RunAndReturn(run func() error) *MockChatCompletionStream_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockChatCompletionStream
func (_mock *MockChatCompletionStream) Next() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockChatCompletionStream_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockChatCompletionStream_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockChatCompletionStream_Expecter) Next() *MockChatCompletionStream_Next_Call {
	return &MockChatCompletionStream_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockChatCompletionStream_Next_Call) Run(run func()) *MockChatCompletionStream_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatCompletionStream_Next_Call) Return(b bool) *MockChatCompletionStream_Next_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockChatCompletionStream_Next_Call) RunAndReturn(run func() bool) *MockChatCompletionStream_Next_Call {
	_c.Call.Return(run)
	return _c
}
