// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raphael-foliveira/tca/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckpointsRepository creates a new instance of MockCheckpointsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckpointsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckpointsRepository {
	mock := &MockCheckpointsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckpointsRepository is an autogenerated mock type for the CheckpointsRepository type
type MockCheckpointsRepository struct {
	mock.Mock
}

type MockCheckpointsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckpointsRepository) EXPECT() *MockCheckpointsRepository_Expecter {
	return &MockCheckpointsRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCheckpointsRepository
func (_mock *MockCheckpointsRepository) Create(ctx context.Context, checkpoint models.Checkpoint) (models.Checkpoint, error) {
	ret := _mock.Called(ctx, checkpoint)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint) (models.Checkpoint, error)); ok {
		return returnFunc(ctx, checkpoint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint) models.Checkpoint); ok {
		r0 = returnFunc(ctx, checkpoint)
	} else {
		r0 = ret.Get(0).(models.Checkpoint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Checkpoint) error); ok {
		r1 = returnFunc(ctx, checkpoint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckpointsRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCheckpointsRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpoint models.Checkpoint
func (_e *MockCheckpointsRepository_Expecter) Create(ctx interface{}, checkpoint interface{}) *MockCheckpointsRepository_Create_Call {
	return &MockCheckpointsRepository_Create_Call{Call: _e.mock.On("Create", ctx, checkpoint)}
}

func (_c *MockCheckpointsRepository_Create_Call) Run(run func(ctx context.Context, checkpoint models.Checkpoint)) *MockCheckpointsRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Checkpoint
		if args[1] != nil {
			arg1 = args[1].(models.Checkpoint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckpointsRepository_Create_Call) Return(checkpoint1 models.Checkpoint, err error) *MockCheckpointsRepository_Create_Call {
	_c.Call.Return(checkpoint1, err)
	return _c
}

func (_c *MockCheckpointsRepository_Create_Call) RunAndReturn(run func(ctx context.Context, checkpoint models.Checkpoint) (models.Checkpoint, error)) *MockCheckpointsRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCheckpointsRepository
func (_mock *MockCheckpointsRepository) GetByID(ctx context.Context, id string) (models.Checkpoint, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Checkpoint, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Checkpoint); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Checkpoint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckpointsRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCheckpointsRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCheckpointsRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCheckpointsRepository_GetByID_Call {
	return &MockCheckpointsRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCheckpointsRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockCheckpointsRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckpointsRepository_GetByID_Call) Return(checkpoint models.Checkpoint, err error) *MockCheckpointsRepository_GetByID_Call {
	_c.Call.Return(checkpoint, err)
	return _c
}

func (_c *MockCheckpointsRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (models.Checkpoint, error)) *MockCheckpointsRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBySessionID provides a mock function for the type MockCheckpointsRepository
func (_mock *MockCheckpointsRepository) GetLatestBySessionID(ctx context.Context, sessionID string) (models.Checkpoint, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBySessionID")
	}

	var r0 models.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Checkpoint, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Checkpoint); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(models.Checkpoint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckpointsRepository_GetLatestBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBySessionID'
type MockCheckpointsRepository_GetLatestBySessionID_Call struct {
	*mock.Call
}

// GetLatestBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockCheckpointsRepository_Expecter) GetLatestBySessionID(ctx interface{}, sessionID interface{}) *MockCheckpointsRepository_GetLatestBySessionID_Call {
	return &MockCheckpointsRepository_GetLatestBySessionID_Call{Call: _e.mock.On("GetLatestBySessionID", ctx, sessionID)}
}

func (_c *MockCheckpointsRepository_GetLatestBySessionID_Call) Run(run func(ctx context.Context, sessionID string)) *MockCheckpointsRepository_GetLatestBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckpointsRepository_GetLatestBySessionID_Call) Return(checkpoint models.Checkpoint, err error) *MockCheckpointsRepository_GetLatestBySessionID_Call {
	_c.Call.Return(checkpoint, err)
	return _c
}

func (_c *MockCheckpointsRepository_GetLatestBySessionID_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (models.Checkpoint, error)) *MockCheckpointsRepository_GetLatestBySessionID_Call {
	_c.Call.Return(run)
	return _c
}
