// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLLMService creates a new instance of MockLLMService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMService {
	mock := &MockLLMService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLLMService is an autogenerated mock type for the LLMService type
type MockLLMService struct {
	mock.Mock
}

type MockLLMService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMService) EXPECT() *MockLLMService_Expecter {
	return &MockLLMService_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function for the type MockLLMService
func (_mock *MockLLMService) Invoke(ctx context.Context, sessionID string, newMessage string) (string, error) {
	ret := _mock.Called(ctx, sessionID, newMessage)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, sessionID, newMessage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, sessionID, newMessage)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, sessionID, newMessage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLLMService_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type MockLLMService_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - newMessage string
func (_e *MockLLMService_Expecter) Invoke(ctx interface{}, sessionID interface{}, newMessage interface{}) *MockLLMService_Invoke_Call {
	return &MockLLMService_Invoke_Call{Call: _e.mock.On("Invoke", ctx, sessionID, newMessage)}
}

func (_c *MockLLMService_Invoke_Call) Run(run func(ctx context.Context, sessionID string, newMessage string)) *MockLLMService_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLLMService_Invoke_Call) Return(s string, err error) *MockLLMService_Invoke_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLLMService_Invoke_Call) RunAndReturn(run func(ctx context.Context, sessionID string, newMessage string) (string, error)) *MockLLMService_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// InvokeStream provides a mock function for the type MockLLMService
func (_mock *MockLLMService) InvokeStream(ctx context.Context, sessionID string, newMessage string, onChunk func(content string)) error {
	ret := _mock.Called(ctx, sessionID, newMessage, onChunk)

	if len(ret) == 0 {
		panic("no return value specified for InvokeStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, func(content string)) error); ok {
		r0 = returnFunc(ctx, sessionID, newMessage, onChunk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLLMService_InvokeStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeStream'
type MockLLMService_InvokeStream_Call struct {
	*mock.Call
}

// InvokeStream is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - newMessage string
//   - onChunk func(content string)
func (_e *MockLLMService_Expecter) InvokeStream(ctx interface{}, sessionID interface{}, newMessage interface{}, onChunk interface{}) *MockLLMService_InvokeStream_Call {
	return &MockLLMService_InvokeStream_Call{Call: _e.mock.On("InvokeStream", ctx, sessionID, newMessage, onChunk)}
}

func (_c *MockLLMService_InvokeStream_Call) Run(run func(ctx context.Context, sessionID string, newMessage string, onChunk func(content string))) *MockLLMService_InvokeStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 func(content string)
		if args[3] != nil {
			arg3 = args[3].(func(content string))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLLMService_InvokeStream_Call) Return(err error) *MockLLMService_InvokeStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLLMService_InvokeStream_Call) RunAndReturn(run func(ctx context.Context, sessionID string, newMessage string, onChunk func(content string)) error) *MockLLMService_InvokeStream_Call {
	_c.Call.Return(run)
	return _c
}
