// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raphael-foliveira/tca/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionsRepository creates a new instance of MockSessionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsRepository {
	mock := &MockSessionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionsRepository is an autogenerated mock type for the SessionsRepository type
type MockSessionsRepository struct {
	mock.Mock
}

type MockSessionsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsRepository) EXPECT() *MockSessionsRepository_Expecter {
	return &MockSessionsRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockSessionsRepository
func (_mock *MockSessionsRepository) GetByID(ctx context.Context, id string) (models.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionsRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSessionsRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionsRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSessionsRepository_GetByID_Call {
	return &MockSessionsRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSessionsRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockSessionsRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionsRepository_GetByID_Call) Return(session models.Session, err error) *MockSessionsRepository_GetByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionsRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (models.Session, error)) *MockSessionsRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
