// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raphael-foliveira/tca/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSummarizer creates a new instance of MockSummarizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSummarizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSummarizer {
	mock := &MockSummarizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSummarizer is an autogenerated mock type for the Summarizer type
type MockSummarizer struct {
	mock.Mock
}

type MockSummarizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSummarizer) EXPECT() *MockSummarizer_Expecter {
	return &MockSummarizer_Expecter{mock: &_m.Mock}
}

// Summarize provides a mock function for the type MockSummarizer
func (_mock *MockSummarizer) Summarize(ctx context.Context, checkpoint models.Checkpoint) (models.Checkpoint, error) {
	ret := _mock.Called(ctx, checkpoint)

	if len(ret) == 0 {
		panic("no return value specified for Summarize")
	}

	var r0 models.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint) (models.Checkpoint, error)); ok {
		return returnFunc(ctx, checkpoint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Checkpoint) models.Checkpoint); ok {
		r0 = returnFunc(ctx, checkpoint)
	} else {
		r0 = ret.Get(0).(models.Checkpoint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Checkpoint) error); ok {
		r1 = returnFunc(ctx, checkpoint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSummarizer_Summarize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Summarize'
type MockSummarizer_Summarize_Call struct {
	*mock.Call
}

// Summarize is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpoint models.Checkpoint
func (_e *MockSummarizer_Expecter) Summarize(ctx interface{}, checkpoint interface{}) *MockSummarizer_Summarize_Call {
	return &MockSummarizer_Summarize_Call{Call: _e.mock.On("Summarize", ctx, checkpoint)}
}

func (_c *MockSummarizer_Summarize_Call) Run(run func(ctx context.Context, checkpoint models.Checkpoint)) *MockSummarizer_Summarize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Checkpoint
		if args[1] != nil {
			arg1 = args[1].(models.Checkpoint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSummarizer_Summarize_Call) Return(checkpoint1 models.Checkpoint, err error) *MockSummarizer_Summarize_Call {
	_c.Call.Return(checkpoint1, err)
	return _c
}

func (_c *MockSummarizer_Summarize_Call) RunAndReturn(run func(ctx context.Context, checkpoint models.Checkpoint) (models.Checkpoint, error)) *MockSummarizer_Summarize_Call {
	_c.Call.Return(run)
	return _c
}
