// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenCounter creates a new instance of MockTokenCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenCounter {
	mock := &MockTokenCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenCounter is an autogenerated mock type for the TokenCounter type
type MockTokenCounter struct {
	mock.Mock
}

type MockTokenCounter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenCounter) EXPECT() *MockTokenCounter_Expecter {
	return &MockTokenCounter_Expecter{mock: &_m.Mock}
}

// CountTokens provides a mock function for the type MockTokenCounter
func (_mock *MockTokenCounter) CountTokens(text string) int64 {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for CountTokens")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockTokenCounter_CountTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTokens'
type MockTokenCounter_CountTokens_Call struct {
	*mock.Call
}

// CountTokens is a helper method to define mock.On call
//   - text string
func (_e *MockTokenCounter_Expecter) CountTokens(text interface{}) *MockTokenCounter_CountTokens_Call {
	return &MockTokenCounter_CountTokens_Call{Call: _e.mock.On("CountTokens", text)}
}

func (_c *MockTokenCounter_CountTokens_Call) Run(run func(text string)) *MockTokenCounter_CountTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenCounter_CountTokens_Call) Return(n int64) *MockTokenCounter_CountTokens_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTokenCounter_CountTokens_Call) RunAndReturn(run func(text string) int64) *MockTokenCounter_CountTokens_Call {
	_c.Call.Return(run)
	return _c
}
